### ISSUE TITLE
pkgin fails when /var is >2TB

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#28]
[root@e62cee83-cfcd-429c-9c56-4c33b367deb3 ~]# pkgin in scmgit
calculating dependencies... done.
pkgin: Can't statvfs() `/var/db/pkgin/cache': Value too large for defined data type

We're calling statvfs(), which is not the largefile interface.  This works fine with a quota on the dataset.

This from base 1.8.4.

**Comment by iMilnb** [comment]
Hi, could you give pkgin's version please (pkgin -v) ? if version < 0.6.2.2 could you upgrade it? if version == 0.6.2.2 could you try building / running pkgin's WIP? http://pkgsrc-wip.cvs.sourceforge.net/viewvc/pkgsrc-wip/wip/pkgin/

Thanks

**Comment by ghost** [comment]
pkgin -v says 0.6.0.  This is with dataset base-1.8.4; there is nothing newer, and I've verified that this pkgin is the newest available in the 1.8.4 repo.  I'll coordinate with jperkin or others to figure out how to test a newer version of pkgin itself in this environment.

**Comment by jperkin** [comment]
Same problem with 0.6.2.2.  @iMilnb while we're here, can you update wip to include the MACHINE_ARCH bits I put into pkgsrc?  They are required to ensure the correct ABI is picked, and I don't want them lost when wip is merged.  A cleaner fix in pkgin itself would be better, of course :)

I'll look at fixing the statvfs problem.

**Comment by jperkin** [comment]
@iMilnb 

```
Index: Makefile.in
===================================================================
RCS file: /cvsroot/pkgin/pkgin/Makefile.in,v
retrieving revision 1.20
diff -u -r1.20 Makefile.in
--- Makefile.in 13 Jun 2012 13:50:16 -0000  1.20
+++ Makefile.in 10 Dec 2012 18:13:16 -0000
@@ -75,7 +75,7 @@
        -DPKGTOOLS=\"${PKGTOOLS}\"

 CPPFLAGS+= -DHAVE_CONFIG_H
-CPPFLAGS+= -D_LARGEFILE_SOURCE -D_LARGE_FILES
+CPPFLAGS+= -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES
 CPPFLAGS+= -DCHECK_MACHINE_ARCH=\"${MACHINE_ARCH}\"
 CPPFLAGS+= -Iexternal -I. -I${LOCALBASE}/include
```

Are you going to do an update before Q4 branch or should I bodge something in the pkgsrc Makefile for now?

**Comment by iMilnb** [comment]
@jperkin I wish to, my plan is to sync WIP with pkgsrc (including your changes) during this week.

Regarding the diff, I removed -D_FILE_OFFSET_BITS=64 from the main Makefile.in some time ago because it caused libfetch to fail under SmartOS IIRC, instead I've added:

#define FILE_OFFSET_BITS 64 /\* needed for large filesystems on sunos */

in fsops.c. On a second read, it may be missing an underscore :)

**Comment by iMilnb** [comment]
Please try pkgin 0.6.3.1 from pkgsrc current (soon to be freezed as 2012Q4), it should fix that issue.

**Comment by jperkin** [comment]
Confirmed, pkgin 0.6.3.1 works fine, thanks.

**Comment by jperkin** [comment]
Sorry, this isn't actually fixed, I must have somehow tested the wrong binary..

Due to the way the includes are parsed putting it directly in fsops.c does not work.  I think we should go with the original fix of passing `-D_FILE_OFFSET_BITS=64` and fixing any resulting fallout (which is probably broken behaviour anyway).

For now I've done this in our tree: https://github.com/joyent/pkgsrc/commit/1e7673879a398d4cadb9774e29a581056fa661f2

**Comment by mamash** [comment]
This should have been fixed properly earlier last year:

https://github.com/joyent/pkgsrc/commit/5d53be313517b1cbc5f7fff6f867c64d9a76bea2
