### ISSUE TITLE
py27-OpenSSL complains about SSLv2_server_method:

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#339]
```
>>> from OpenSSL import SSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/opt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: ld.so.1: python2.7: fatal: relocation error: file /opt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: symbol SSLv2_server_method: referenced symbol not found

```

To reproduce:
pkgin in py27-OpenSSL
python
from OpenSSL import SSL

**Comment by sjorge** [comment]
I am using 15.4.0, I already force reinstalled python27 to fix the linking issues. I also tried a force reinstall of pyopenssl but because it was never installed to begin with, this didn't help

**Comment by jjlawren** [comment]
Affects all python versions. Identical problem when testing with py35-cryptography module.

**Comment by jjlawren** [comment]
Hmm, mailing list implies this is only fixed in 15.4.1 and later: https://www.listbox.com/member/archive/184463/2016/03/sort/time_rev/page/6/entry/1:256/20160314053256:B99921DE-E9C7-11E5-A290-37A9F010038B/

**Comment by sjorge** [comment]
Yes, but that package is not installed by default (python27 is). Also force reinstall does not fix it, which fixes all the other packages I found on 15.4.0.

**Comment by jjlawren** [comment]
I provisioned a minimal-64 15.4.1 image and it still has the same SSLv2 problem when using the py35-cryptography package:
`ImportError: ld.so.1: python3.5: fatal: relocation error: file /opt/local/lib/python3.5/site-packages/cryptography/hazmat/bindings/_openssl.so: symbol SSLv2_server_method: referenced symbol not found`

**Comment by jperkin** [comment]
The problem is that the py-cryptography package no longer builds against the newer OpenSSL API, e.g.:

  http://us-east.manta.joyent.com/pkgsrc/public/reports/2015Q4/i386/20160318.1327/py27-cryptography-1.1.2/build.log

so any install is actually picking up the old package.  I'll look at backporting the fixes from trunk.

**Comment by mamash** [comment]
This should be fixed by one of the recent 2014Q4 rebuilds (e.g. there's a new backported cryptography package).
